name: tests

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
  schedule:
    - cron: '14 7 * * 0'  # run once a week on Sunday
  workflow_dispatch:

jobs:
  deploy-github-release:
    # only deploy on tags, see https://stackoverflow.com/a/58478262/1320237
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: github-release
    steps:
      - uses: actions/checkout@v4
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          body: To view the changes, please see the
            [Changelog](https://icalendar.readthedocs.io/en/latest/changelog.html).
            This release can be installed from
            [PyPI](https://pypi.org/project/icalendar/#history).
